### ISSUE TITLE
`<html lang="ja">` or include Japanese-only fonts

### ISSUE THREAD

**Issue by patarapolw** [Ambiwlans/JiKen#16]
This is important, as many Kanji have different shapes due to [Han Unification](https://en.wikipedia.org/wiki/Han_unification#Examples_of_language-dependent_glyphs). Chinese variant of a Kanji is of course outside the range a native, at least, should recognize the Kanji.

**Comment by Ambiwlans** [comment]
I couldn't find a situation where this could occur, but I changed it anyways to be on the safe side.

**Comment by Ambiwlans** [comment]
I couldn't find a situation where this could occur, but I changed it anyways to be on the safe side.
