### ISSUE TITLE
Three or Four input boxes / checks, for more accurate calculations (and reduce bias)

### ISSUE THREAD

**Issue by patarapolw** [Ambiwlans/JiKen#17]
Those `<input type="text">` would be

1. Meanings
2. On readings
3. Kun readings
4. Associate vocabularies

**Comment by Ambiwlans** [comment]
I'm not sure what you're asking for here. Like, each card, the user can check off which features they knew?

**Comment by patarapolw** [comment]
Maybe, 2 or more cards for each Kanji.

**Comment by Ambiwlans** [comment]
I think it goes a bit out of scope for the simplicity of 'yes, no, next' for this project. I could probably get more accurate estimates by abandoning the pure sigmoid assumption with the data i already have and leveraging related kanji .... but for most users <3000 kanji it seems pretty accurate as is. If I were to require more user input to improve speed, I'd have the user give an initial guess at how many they know. That'd probably speed things up by 3~5 guesses. Other users didn't like the idea though.

The input is appreciated!
